# Generated by Django 3.2.17 on 2023-06-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userloginactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginactivity',
            name='login_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
