# Generated by Django 3.2.17 on 2023-06-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userloginactivity_login_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginactivity',
            name='login_num',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
